[format]
dedup = false
delim = " "
client = "{icon}{delim}"
client_active = "<span color='#74c7ec'>{icon}</span>"
workspace = "<span color='#74c7ec'>{id}:</span>{delim}{clients}"
workspace_empty = "<span color='#74c7ec'>{id}</span>{delim}{clients}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon}]{delim}"

[icons_active]
DEFAULT="{icon}"

[icons]
DEFAULT = 'ó°³¤'

# Vim
'/nvim ?\w*/' = 'î˜«'
'/vim ?\w*/' = 'î˜«'
'Neovide' = 'î˜«'

# Firefox
'/(?i)Github.*Firefox/' = 'ï„“'
'/(?i)YouTube.*Firefox/' = 'ï…ª'
'firefox' = 'ï‰©'
'firefox-nightly' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'

# Steam
'steam_app?\w*/' = 'ï„›'
'Steam' = 'ï†¶'
'steamwebhelper' = 'ï†¶'

# Terminals
'Alacritty' = 'ï„ '
'foot' = 'ï„ '
'foot-client' = 'ï„ '
'kitty' = 'ï„ '

# Misc Using
'/Minecraft?\w*/' = 'ó°³'
'/YouTube Music/' = 'ï€'
'/node/' = 'ó°™'
'/npm/' = 'ó°™'
'/swayimg?\w*/' = 'ï€¾'
'/yarn/' = 'ó°™'
'Code' = 'ï„¡'
'org.fritzing.Fritzing' = 'îª¾'
'Fritzing' = 'îª¾'
'BurgerğŸ”ğŸ‘' = 'ó°š…'
'balena-etcher' = 'ï‹›'
'blueman-manager' = 'ïŠ”'
'com/.https://ultimaker.Ultimaker-Cura' = 'ï†³'
'cura' = 'ï†³'
'discord' = 'ó°™¯'
'factorio' = 'ï€“'
'gamescope' = 'ï„›'
'gcr-prompter' = 'ï€£'
'krita' = 'ï‡¼'
'nemo' = 'ï»'
'xdg-desktop-portal-gtk' = 'ï»'
'mpv' = 'ï€½'
'nm-connection-editor' = 'ï›¿'
'org.freecadweb.FreeCAD' = 'ï†²'
'FreeCAD' = 'ï†²'
'org.telegram.desktop' = 'îˆ—'
'org.gnome.baobab' = 'ó°‹Š'
'org.kde.kcolorchooser' = 'ï‡»'
'org.kde.kdeconnect-settings' = 'ï'
'org.kde.kdeconnect.app' = 'ï'
'org.prismlauncher.PrismLauncher' = 'ó°³'
'osu!' = 'ó°²¡'
'swappy' = 'ï‡¼'

# Misc default
'Bitwarden' = 'ï‚„'
'Chia Blockchain' = 'ï“˜'
'Chromium' = 'ï‰¨'
'GitHub Desktop' = 'ï„“'
'Google-chrome' = 'ï‰¨'
'Insomnia' = 'ïˆ¶'
'Postman' = 'ï '
'Slack' = 'ï†˜'
'Spotify' = 'ï†¼'
'Thunderbird' = 'ïƒ '
'code-oss' = 'ï„¡'
'jetbrains-studio' = 'ï„¡'
'org.qbittorrent.qBittorrent' = 'ï¶'
'thunderbird' = 'ïƒ '
'vlc' = 'ï€½'

