# Make sure you got that NerdFonts in your fonts.

fallback = 'ó°³¤'

[matching]

# Vim
'/nvim ?\w*/' = 'îš®'
'/NVIM ?\w*/' = 'îš®'
'/vim ?\w*/' = 'î˜«'
'Neovide' = 'îš®'
'neovide' = 'îš®'

# Other editors
'Code' = 'ó°¨'
'code-oss' = 'ó°¨'
'gedit' = 'ó±©¼'
'org.kde.kate' = 'ó±©¼'

# Firefox
'/(?i)Github.*Firefox/' = 'ï„“'
'/(?i)YouTube.*Firefox/' = 'ó°—ƒ'
'/Mozilla Crash Reporter/' = 'ó°ˆ¹'
'firefox' = 'ó°ˆ¹'
'firefox-nightly' = 'ó°ˆ¹'
'firefoxdeveloperedition' = 'ó°ˆ¹'
'firefoxnightly' = 'ó°ˆ¹'

'/YouTube Music/' = 'ï€'
'YouTube Music' = 'ï€'

# Steam
'/Steam/' = 'ï†¶'
'Steam' = 'ï†¶'
'steam' = 'ï†¶'
'steamwebhelper' = 'ï†¶'

# Steam apps
'steam_app_218230' = 'ğŸ¤¡' # Planetside 2
'steam_app_220200' = 'ï§'  # Kerbal Space Program
'steam_app_242680' = 'îˆ¸'  # Nuclear Throne
'steam_app_271590' = 'V'  # Grand Theft Auto V
'steam_app_275850' = 'ï†—'  # No Man's Sky
'steam_app_548430' = 'ïƒ¼'  # DeepRock
'steam_app_553850' = 'ó°š‘'  # HELLDIVERSâ„¢ 2
'steam_app_782330' = 'ï„›'  # Doom Eternal
'steam_app_1268750' = 'ï„›' # Starship Troopers: Extermination
'steam_app_1332010' = 'ó°„›' # Stray
'steam_app_1454400' = 'ó°†˜' # Cookie clicker
'steam_app_1966720' = 'ï±' # Lethal Company
'steam_app_2093940' = 'ó°Šœ' # Vivid/Stasis
'steam_app_1794680' = 'ó°³¬' # Vampire Survivors

# Other games
'/Minecraft?\w*/' = 'ó°³'
'/nuclearthrone/' = 'îˆ¸'
'BeamNG.drive.x64' = 'ó°ª'
'factorio' = 'ï€“'
'gamescope' = 'ï„›'
'lutris' = 'ï„›'
'osu!' = 'ó°²¡'
'osu!.exe' = 'ó°²¡'
'vampiresurvivors.exe' = 'ó°³¬'
'vividstasis.exe' = 'ó°Šœ'

# Terminals
'Alacritty' = 'ï„ '
'foot' = 'ï„ '
'foot-client' = 'ï„ '
'footclient' = 'ï„ '
'kitty' = 'ï„ '
'/kitty/' = 'ï„ '

# Discord
'de.shorsh.discord-screenaudio' = 'ï‡¿'
'discord' = 'ï‡¿'
'vesktop' = 'ï‡¿'
'Vesktop' = 'ï‡¿'
'VencordDesktop' = 'ï‡¿'

# CAD ó°»¬
'org.freecadweb.FreeCAD' = 'ïŒ¶'
'org.freecad.FreeCAD' = 'ïŒ¶'
'FreeCAD' = 'ïŒ¶'
'Ondsel ES' = 'ïŒ¶'

# Slicer
'PrusaSlicer' = 'ó°†§'
'cura' = 'ó°†§'
'com/.https://ultimaker.Ultimaker-Cura' = 'ï†³'

# Mail
'Thunderbird' = 'ïƒ '
'thunderbird' = 'ïƒ '
'betterbird' = 'ïƒ '

# Wine
'wineboot.exe' = 'ó°¡¶'
'control.exe' = 'ó°¡¶'

# Video players
'vlc' = 'ó°•¼'
'mpv' = 'ï®'
'MPlayer' = 'ï€½'

# JS
'/yarn/' = 'ó°™'
'/node/' = 'ó°™'
'/npm/' = 'ó°™'

# Image manipulators
'gmic' = 'ó±‡£'
'krita' = 'ï‡¼'
'swappy' = 'ï‡¼'
'flameshot' = 'ï‡¼'

'/swayimg?\w*/' = 'ï€¾'
'org.kde.koko' = 'ï€¾'

# File explorers
'/Open Files/' = 'ï“”'
'Xdg-desktop-portal-gtk' = 'ï“”'
'nemo' = 'ï“”'
'xdg-desktop-portal-gtk' = 'ï“”'

'file-roller' = 'ï‡†'
'org.gnome.FileRoller' = 'ï‡†'
'org.kde.ark' = 'ï‡†'

'balena-etcher' = 'ó±Š'
'Ventoy2Disk.gtk3' = 'ó±Š'

# Audio
'com.github.wwmm.easyeffects' = 'ï‡‡'
'pavucontrol' = 'ï‡‡'

'org.rncbc.qjackctl' = 'ó±¡«'
'org.rncbc.qpwgraph' = 'ó±¡«'

'libreoffice-calc'= 'ó±'

# Misc Using
'/NoiseTorch/' = 'ó°¯'
'/com.nextcloud.desktopclient.nextcloud/' = 'ïƒ‚'
'/glxgears/' = 'ï‚…'
'BurgerğŸ”ğŸ‘' = 'ó°š…'
'Chromium' = 'ï‰¨'
'Fritzing' = 'îª¾'
'NoiseTorch' = 'ó°¯'
'blueman-manager' = 'ïŠ”'
'com.nextcloud.desktopclient.nextcloud' = 'ïƒ‚'
'com.obsproject.Studio' = 'ó°‘‹'
'gcr-prompter' = 'ï€£'
'gcr-viewer' = 'ó°„¤'
'gnome-font-viewer' = 'î™™'
'huawei configuration encryption and decryption tools.exe' = 'ó°Œ‹'
'nm-connection-editor' = 'ï›¿'
'nwg-look' = 'ïƒ'
'org.fritzing.Fritzing' = 'îª¾'
'org.gnome.Calendar' = 'ó°ƒ­'
'org.gnome.baobab' = 'ó°‹Š'
'org.gnome.font-viewer' = 'î™™'
'org.gnome.tweaks' = 'ïƒ'
'org.kde.kcoimage manipulationlorchooser' = 'ï‡»'
'org.kde.kdeconnect-settings' = 'ï'
'org.kde.kdeconnect.app' = 'ï'
'org.kde.kdeconnect.daemon' = 'ï'
'org.prismlauncher.PrismLauncher' = 'ó°³'
'org.telegram.desktop' = 'îˆ—'
'piper' = 'ó°½'
'polkit-gnome-authentication-agent-1' = 'ó°Œ‹'
'qt5ct' = 'ïƒ'
'qt6ct' = 'ïƒ'
'seahorse' = 'ó°Œ‹'
'virt-manager' = 'ï„ˆ'
'io.missioncenter.MissionCenter' = 'ï·'

# Misc default
'Bitwarden' = 'ï‚„'
'Chia Blockchain' = 'ï“˜'
'GitHub Desktop' = 'ï„“'
'Google-chrome' = 'ï‰¨'
'Insomnia' = 'ïˆ¶'
'Postman' = 'ï '
'Slack' = 'ï†˜'
'Spotify' = 'ï†¼'
'jetbrains-studio' = 'ï„¡'
'org.qbittorrent.qBittorrent' = 'ï¶'

