fallback = 'ó°³¤'

[matching]

# Vim
'/nvim ?\w*/' = 'î˜«'
'/vim ?\w*/' = 'î˜«'
'Neovide' = 'î˜«'

# Firefox
'/(?i)Github.*Firefox/' = 'ï„“'
'/(?i)YouTube.*Firefox/' = 'ï…ª'
'firefox' = 'ï‰©'
'firefox-nightly' = 'ï‰©'
'firefoxnightly' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'

# Steam
'steam' = 'ï†¶'
'Steam' = 'ï†¶'
'/Steam/' = 'ï†¶'
'steamwebhelper' = 'ï†¶'

# Steam apps
'steam_app_1454400' = 'ó°†˜' # Cookie clicker
'steam_app_1332010' = 'ó°„›' # Stray
'steam_app_548430' = 'ïƒ¼' # DeepRock
'steam_app_1966720' = 'ï±' # Lethal Company
'vividstasis.exe' = 'ó°Šœ' # Vivid/Stasis
'steam_app_2093940' = 'ó°Šœ' # Vivid/Stasis
'steam_app_275850' = 'ï†—' # No Man's Sky

# Terminals
'Alacritty' = 'ï„ '
'foot' = 'ï„ '
'foot-client' = 'ï„ '
'footclient' = 'ï„ '
'kitty' = 'ï„ '

# Discord
'discord' = 'ó°™¯'
'vesktop' = 'ó°™¯'
'VencordDesktop' = 'ó°™¯'

# Flameshot
'flameshot' = 'ï”Œ'

# 3D printing
'org.freecadweb.FreeCAD' = 'ï†²'
'org.freecad.FreeCAD' = 'ï†²'
'FreeCAD' = 'ï†²'
'cura' = 'ó°†§'

# Mail
'Thunderbird' = 'ïƒ '
'betterbird' = 'ïƒ '

# osu!
'osu!.exe' = 'ó°²¡'
'osu!' = 'ó°²¡'

# Wine
'wineboot.exe' = 'ó°¡¶'

# Misc Using
'org.kde.ark' = 'ï‡†'
'com.nextcloud.desktopclient.nextcloud' = 'ïƒ‚'
'Xdg-desktop-portal-gtk' = 'ï“”'
'piper' = 'ó°½'
'gmic' = 'ó±‡£'
'NoiseTorch' = 'ó°¯'
'/Minecraft?\w*/' = 'ó°³'
'/YouTube Music/' = 'ï€'
'/node/' = 'ó°™'
'/npm/' = 'ó°™'
'/swayimg?\w*/' = 'ï€¾'
'/yarn/' = 'ó°™'
'Code' = 'ï„¡'
'org.fritzing.Fritzing' = 'îª¾'
'Fritzing' = 'îª¾'
'BurgerğŸ”ğŸ‘' = 'ó°š…'
'balena-etcher' = 'ï‹›'
'blueman-manager' = 'ïŠ”'
'com/.https://ultimaker.Ultimaker-Cura' = 'ï†³'
'factorio' = 'ï€“'
'gamescope' = 'ï„›'
'gcr-prompter' = 'ï€£'
'krita' = 'ï‡¼'
'nemo' = 'ï»'
'file-roller' = 'ó°›«'
'xdg-desktop-portal-gtk' = 'ï»'
'mpv' = 'ï€½'
'nm-connection-editor' = 'ï›¿'
'org.telegram.desktop' = 'îˆ—'
'org.gnome.baobab' = 'ó°‹Š'
'org.kde.kcolorchooser' = 'ï‡»'
'org.kde.kdeconnect-settings' = 'ï'
'org.kde.kdeconnect.app' = 'ï'
'org.prismlauncher.PrismLauncher' = 'ó°³'
'swappy' = 'ï‡¼'

# Misc default
'Bitwarden' = 'ï‚„'
'Chia Blockchain' = 'ï“˜'
'Chromium' = 'ï‰¨'
'GitHub Desktop' = 'ï„“'
'Google-chrome' = 'ï‰¨'
'Insomnia' = 'ïˆ¶'
'Postman' = 'ï '
'Slack' = 'ï†˜'
'Spotify' = 'ï†¼'
'code-oss' = 'ï„¡'
'jetbrains-studio' = 'ï„¡'
'org.qbittorrent.qBittorrent' = 'ï¶'
'thunderbird' = 'ïƒ '
'vlc' = 'ï€½'

