fallback = 'ï—'

[matching]

# Vim
'/nvim ?\w*/' = 'î˜«'
'/vim ?\w*/' = 'î˜«'
'Neovide' = 'î˜«'

# Firefox
'/(?i)Github.*Firefox/' = 'ï„“'
'/(?i)YouTube.*Firefox/' = 'ï…ª'
'firefox' = 'ï‰©'
'Nightly' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'

# Steam
'steam_app?\w*/' = 'ï„›'
'Steam' = 'ï†¶'

# Terminals
'Alacritty' = 'ï„ '
'foot' = 'ï„ '
'foot-client' = 'ï„ '
'kitty' = 'ï„ '

# Misc Using
'/Minecraft?\w*/' = 'ï¡²'
'/YouTube Music/' = 'ï€ '
'/node/' = 'ï¢˜'
'/npm/' = 'ï¢˜'
'/swayimg?\w*/' = 'ï€¾'
'/yarn/' = 'ï¢˜'
'Code' = 'ï„¡'
'org.fritzing.Fritzing' = 'ï’“'
'Fritzing' = 'ï’“'
'BurgerğŸ”ğŸ‘' = 'ó°š…'
'balena-etcher' = 'ï‹›'
'blueman-manager' = 'ïŠ”'
'com/.https://ultimaker.Ultimaker-Cura' = 'ï†³'
'cura' = 'ï†³'
'discord' = 'ï­®'
'factorio' = 'ï€“'
'gamescope' = 'ï„›'
'gcr-prompter' = 'ï€£'
'krita' = 'ï‡¼'
'nemo' = 'ï»'
'xdg-desktop-portal-gtk' = 'ï»'
'mpv' = 'ï€½'
'nm-connection-editor' = 'ï›¿'
'org.freecadweb.FreeCAD' = 'ï†²'
'FreeCAD' = 'ï†²'
'org.gnome.baobab' = 'ïŸ‰'
'org.kde.kcolorchooser' = 'ï‡»'
'org.kde.kdeconnect-settings' = 'ï'
'org.kde.kdeconnect.app' = 'ï'
'org.prismlauncher.PrismLauncher' = 'ï¡²'
'osu!' = 'ï„‘'
'swappy' = 'ï‡¼'

# Misc default
'Bitwarden' = 'ï‚„'
'Chia Blockchain' = 'ï“˜'
'Chromium' = 'ï‰¨'
'GitHub Desktop' = 'ï„“'
'Google-chrome' = 'ï‰¨'
'Insomnia' = 'ïˆ¶'
'Postman' = 'ï '
'Slack' = 'ï†˜'
'Spotify' = 'ï†¼'
'Thunderbird' = 'ïƒ '
'code-oss' = 'ï„¡'
'jetbrains-studio' = 'ï„¡'
'org.qbittorrent.qBittorrent' = 'ï¶'
'thunderbird' = 'ïƒ '
'vlc' = 'ï€½'

